Repository Azure/sap-hana, pull requests merged in 2018-10, with the labels that each got.

#58 set default for url_xs_services
  deploy/vm/modules/ha_pair/variables.tf
Labels: bug

#60 Make service principal a user input rather than creating on each depl…
  README.md
  deploy/vm/ansible/roles/stonith-device-creation/defaults/main.yml
  deploy/vm/ansible/roles/stonith-device-creation/tasks/main.yml
  deploy/vm/modules/ha_pair/main.tf
  deploy/vm/modules/ha_pair/variables.tf
  deploy/vm/modules/playbook-execution/main.tf
  deploy/vm/modules/playbook-execution/variables.tf
Labels: bug

#55 Ansible playbook for testing using hdbsql
  deploy/vm/test/hdbsql/hdbsql_playbook.yml
  deploy/vm/test/hdbsql/roles/datagen/defaults/main.yml
  deploy/vm/test/hdbsql/roles/datagen/tasks/main.yml
  deploy/vm/test/hdbsql/roles/datagen/templates/crossjoin.sql.j2
Labels: Test

#67 Completely re-wrote README
  README.md
  downloads.md
  shine-dashboard.png
  template-hapair.png
Labels: Documentation

#68 Removed PNGs in repo
  shine-dashboard.png
  template-hapair.png
Labels: Documentation

#71 fix single node with spn
  deploy/vm/modules/single_node_hana/single-node-hana.tf
  deploy/vm/modules/single_node_hana/variables.tf
Labels: bug

#76 Documentation for HA pair scenario
  README.md
  deploy/vm/modules/ha_pair/README.md
  deploy/vm/modules/ha_pair/terraform.tfvars.template
Labels: Documentation

#61 parser for hwcct
  deploy/vm/test/hwcct_parser.py
Labels: Test

#56 Ansible script to test using hwcct
  deploy/vm/test/hwcct/hwcct_config.json
  deploy/vm/test/hwcct/hwcct_playbook.yml
Labels: Test
