Repository Azure/sap-hana, pull requests merged in 2019-10, with the labels that each got.

#236 [HOTFIX] lastRunServer cannot be de-serialized anymore
  monitor/sapmon.py
Labels: SapMonitor

#237 Add HANA System Availability check
  monitor/SapHana.json
  monitor/sapmon.py
Labels: SapMonitor

#241 Fix bug with allowed_ips to use list of strings
  deploy/v2/input.json
  deploy/v2/template_samples/single_node_hana.json
  deploy/v2/terraform/modules/jumpbox/main.tf
  templates/tempGen/template.json
Labels: Terraform, bug

#243 Add conversion from bytes to string
  deploy/v2/python_scripts/downloader/SAP_DLM.py
  deploy/v2/python_scripts/downloader/SAP_SMP.py
Labels: bug

#244 Copy SSH key pair to all linux jumpboxes with correct permission
  deploy/v2/input.json
  deploy/v2/template_samples/single_node_hana.json
  deploy/v2/terraform/main.tf
  deploy/v2/terraform/modules/hdb_node/main.tf
  deploy/v2/terraform/modules/hdb_node/variables.tf
  deploy/v2/terraform/modules/jumpbox/main.tf
  deploy/v2/terraform/modules/jumpbox/variables.tf
  deploy/v2/terraform/variables.tf
  templates/tempGen/template.json
Labels: Terraform, bug

#246 [HOTFIX] Add flag enable_secure_transfer to enable secure transfer for all storage account
  deploy/v2/input.json
  deploy/v2/template_samples/single_node_hana.json
  deploy/v2/terraform/main.tf
  deploy/v2/terraform/modules/common_infrastructure/main.tf
  deploy/v2/terraform/modules/common_infrastructure/variables.tf
  deploy/v2/terraform/variables.tf
  templates/tempGen/template.json
Labels: HOTFIX, Terraform

#245 v2: Create/copy Ansible inventory file and install required packages on RTI
  deploy/v2/hdb_sizes.json
  deploy/v2/input.json
  deploy/v2/template_samples/single_node_hana.json
  deploy/v2/terraform/main.tf
  deploy/v2/terraform/modules/jumpbox/main.tf
  deploy/v2/terraform/modules/jumpbox/outputs.tf
  deploy/v2/terraform/modules/jumpbox/variables.tf
  deploy/v2/terraform/modules/output_files/ansible_inventory.tmpl
  deploy/v2/terraform/modules/output_files/main.tf
  deploy/v2/terraform/modules/output_files/outputs.tf
  deploy/v2/terraform/modules/output_files/variables.tf
  deploy/v2/terraform/modules/output_json/outputs.tf
  deploy/v2/terraform/modules/output_json/variables.tf
  templates/tempGen/template.json
Labels: Terraform

#248 Change downloader to take input.json
  deploy/v2/python/downloader/README.MD
  deploy/v2/python/downloader/SAP_DLM.py
  deploy/v2/python/downloader/SAP_SMP.py
  deploy/v2/python/downloader/SAP_Scenarios.py
  deploy/v2/python/downloader/basket.py
  deploy/v2/python/downloader/config_samples/hdb.json
  deploy/v2/python/downloader/config_samples/s4.json
  deploy/v2/python/downloader/helper.py
Labels: enhancement

#249 Add Ansible to v2 pipeline test
  azure-pipelines-v2.yaml
  templates/ansible-deployment-steps.yaml
  templates/tempGen/template.json
  templates/terraform-deployment-steps.yaml
Labels: Test
