Repository Azure/sap-hana, pull requests merged in 2019-07, with the labels that each got.

#170 Test deployment of single node hana using azure pipelines
  CONTRIBUTING.md
  azure-pipelines.yml
  deploy/vm/test/terraform.tfvars
Labels: Test

#177 Automated Deployments include IMDS registration
  deploy/vm/ansible/ha_pair_playbook.yml
  deploy/vm/ansible/roles/imds-reg/defaults/main.yml
  deploy/vm/ansible/roles/imds-reg/tasks/main.yml
  deploy/vm/ansible/single_node_playbook.yml
Labels: Ansible

#186 Fix HA pair by disabling Cloud-Netconfig
  deploy/vm/ansible/ha_pair_playbook.yml
  deploy/vm/ansible/roles/disable-cloud-netconfig/tasks/main.yml
Labels: Ansible

#190 [FIX] Fix calculation of result hash
  monitor/sapmon.py
Labels: bug

#193 [HOTFIX] Assign nsg to subnet to avoid NRMS nsg to be added
  deploy/vm/modules/common_setup/main.tf
  deploy/vm/modules/common_setup/outputs.tf
  deploy/vm/modules/ha_pair/main.tf
  deploy/vm/modules/single_node_hana/single-node-hana.tf
Labels: HOTFIX, bug

#191 [HOTFIX] adding timeout and retries for all content downloads
  deploy/vm/ansible/roles/cockpit-download/tasks/main.yml
  deploy/vm/ansible/roles/saphana-install/tasks/main.yml
  deploy/vm/ansible/roles/set-up-windows-bastion/tasks/main.yml
  deploy/vm/ansible/roles/setup-linux-hana-studio/tasks/main.yml
  deploy/vm/ansible/roles/shine-install/tasks/main.yml
  deploy/vm/ansible/roles/webide-install/tasks/main.yml
  deploy/vm/ansible/roles/xsa-install/tasks/main.yml
  deploy/vm/modules/playbook-execution/main.tf
  deploy/vm/modules/playbook-execution/variables.tf
Labels: HOTFIX

#194 [HOTFIX] Adapt KV name according to new naming convention
  monitor/sapmon.py
Labels: HOTFIX
