Repository Azure/sap-hana, pull requests merged in 2020-12, with the labels that each got.

#969 Add pre-conditions for importing username
  deploy/terraform/bootstrap/sap_deployer/deployer_full.json
  deploy/terraform/terraform-units/modules/sap_deployer/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf
Labels: Terraform

#942 Add waitime before RHEL UNIT starts to create
  .pipeline/tf-release.yml
Labels: Pipeline, enhancement

#970 [BUG] Move spn to kv from deployer to agent
  .pipeline/templates/deployer/post-deployer-steps.yml
  .pipeline/templates/saplandscape/create-saplandscape-steps.yml
  .pipeline/templates/saplib/create-saplib-steps.yml
  .pipeline/templates/saplib/post-saplib-steps.yml
  .pipeline/templates/sapsystem/create-sapsystem-steps.yml
Labels: Pipeline, bug

#971 [BUG] Add missing key_vault in run/sap_library
  .pipeline/templates/saplib/post-saplib-steps.yml
  deploy/terraform/run/sap_deployer/variables_global.tf
  deploy/terraform/run/sap_library/module.tf
Labels: Terraform, bug

#968 [INFRASTRUCTURE] The fault domain count is different per region - application tier fixes
  deploy/configs/max_fault_domain_count.json
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
Labels: enhancement

#974 [INFRASTRUCTURE] The fault domain count is different per region - database tier fixes
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
Labels: enhancement

#975 [OUTPUT] Add the VM Ids to output
  deploy/terraform/run/sap_system/output.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/outputs.tf
Labels: enhancement

#980 Update secret name of username in deployer's output
  deploy/terraform/terraform-units/modules/sap_deployer/output.tf
Labels: Terraform

#979 Fix the broken lookups when size does not exist for that database type
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
Labels: bug

#992 Update the lookup logic to match the db size lookup logic
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
Labels: enhancement

#991 Provide the option to use a non zero based index
  deploy/terraform/run/sap_system/module.tf
  deploy/terraform/run/sap_system/sapsystem_full.json
  deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/vm.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
Labels: enhancement

#948 [ENVIRONMENT] add support for multiple environments
  deploy/terraform/terraform-units/modules/sap_namegenerator/keyvault.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/output.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/resourcegroup.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/vm.tf
Labels: Terraform, enhancement

#1002 Set default for library_environment
  deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf
Labels: Terraform, bug

#1001 Support customer managed keys for encryption
  deploy/terraform/run/sap_system/sapsystem_full.json
  deploy/terraform/terraform-units/modules/sap_deployer/vm-deployer.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-observer.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/vm-anchor.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/vm-hdb.tf
Labels: enhancement

#1007 [INFRASTRUCTURE]Don't create Availability if deploying to an existing…
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/infrastructure.tf
Labels: enhancement

#1005 [INFRASTRUCTURE] Update LoadBalance types to standard for all tiers
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
Labels: enhancement

#1008 [INFRASTRUCTURE]Try reading the SPN KeyVault from override first
  deploy/terraform/bootstrap/sap_library/saplibrary_full.json
  deploy/terraform/bootstrap/sap_library/variables_global.tf
  deploy/terraform/bootstrap/sap_library/variables_local.tf
  deploy/terraform/run/sap_landscape/saplandscape_full.json
  deploy/terraform/run/sap_landscape/variables_local.tf
  deploy/terraform/run/sap_library/saplibrary_full.json
  deploy/terraform/run/sap_library/variables_global.tf
  deploy/terraform/run/sap_library/variables_local.tf
Labels: enhancement

#949 [ENVIRONMENT] Add support for providing the deployer environment as parameter
  deploy/terraform/bootstrap/sap_deployer/module.tf
  deploy/terraform/run/sap_deployer/module.tf
  deploy/terraform/terraform-units/modules/sap_deployer/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/keyvault.tf
Labels: Terraform, enhancement

#1004 Add an indicator about enabling iscsi
  deploy/terraform/terraform-units/modules/sap_landscape/iscsi.tf
  deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_local.tf
Labels: HOTFIX, Terraform

#1014 Update Process Index
  documentation/ansible/system-design-deployment/README.md
  documentation/ansible/system-design-deployment/app/prepare-bom.md
  documentation/ansible/system-design-deployment/app/prepare-full-app-bom.md
  documentation/ansible/system-design-deployment/examples/HANA_1_00_122_v001/bom.yml
  documentation/ansible/system-design-deployment/examples/HANA_2_00_052_v001/bom.yml
  documentation/ansible/system-design-deployment/hana/prepare-bom.md
  documentation/ansible/system-design-deployment/interim-playbook-preparation.md
Labels: Documentation, bug

#1019 Support deployment into existing resource group
  deploy/terraform/terraform-units/modules/sap_deployer/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_deployer/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_deployer/nsg-mgmt.tf
  deploy/terraform/terraform-units/modules/sap_deployer/output.tf
  deploy/terraform/terraform-units/modules/sap_deployer/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_deployer/vm-deployer.tf
Labels: enhancement

#1016 Add yamllint and ansible-lint to deployer
  deploy/terraform/terraform-units/modules/sap_deployer/vm-deployer.tf
Labels: Ansible, Terraform

#1018 Reuse storage account from sap_landscape in sap_system
  deploy/terraform/run/sap_landscape/output.tf
  deploy/terraform/terraform-units/modules/sap_landscape/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/vm-anchor.tf
Labels: Terraform

#1023 Support deployment of SAP_Library to existing resource group
  deploy/terraform/terraform-units/modules/sap_library/variables_local.tf
Labels: enhancement

#1015 [Beta2.3]Scaleout naming
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
Labels: Terraform, bug

#1006 [Beta2.3][INFRASTRUCTURE] Use HA ports for the load balancers
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
Labels: enhancement

#1013 [Beta2.3]refactor the input
  azure-pipelines-daily.yaml
  azure-pipelines.yaml
  deploy/input.json
  deploy/template_samples/application_with_ha.json
  deploy/template_samples/application_with_ha_in_existing_subnet.json
  deploy/template_samples/application_wo_ha.json
  deploy/template_samples/application_wo_ha_customimage.json
  deploy/template_samples/application_wo_ha_windows.json
  deploy/template_samples/clustered_hana.json
  deploy/template_samples/clustered_hana_use_custom_image_with_sbd.json
  deploy/template_samples/clustered_hana_with_sbd.json
  deploy/template_samples/clustered_hana_with_sbd_in_existing_subnet.json
  deploy/template_samples/ha_oracle.json
  deploy/template_samples/rti_only.json
  deploy/template_samples/saplandscaperunner.json
  deploy/template_samples/single_node_hana.json
  deploy/template_samples/single_node_hana_single_container.json
  deploy/template_samples/single_node_hana_with_custom_image.json
  deploy/template_samples/single_node_hana_with_jumpboxes.json
  deploy/template_samples/single_node_hana_with_xsa.json
  deploy/template_samples/single_node_oracle.json
  deploy/template_samples/single_node_oracle_with_custom_image.json
  deploy/terraform/run/sap_system/sapsystem.json
  deploy/terraform/run/sap_system/sapsystem_full.json
  templates/README.MD
  templates/ansible-deployment-steps-daily.yaml
  templates/ansible-deployment-steps.yaml
  templates/job-template-allReuseCases.yaml
  templates/job-template-per-os-daily.yaml
  templates/job-template-per-os.yaml
  templates/tempGen/sap-allNew-APP-HA.json
  templates/tempGen/sap-allNew-APP-SN.json
  templates/tempGen/sap-allNew-AnyDB-HA.json
  templates/tempGen/sap-allNew-AnyDB-SN.json
  templates/tempGen/sap-allNew-HA.json
  templates/tempGen/sap-allNew-SN.json
  templates/tempGen/sap-reuseNSG-SN.json
  templates/tempGen/sap-reuseRG-SN.json
  templates/tempGen/sap-reuseVNET-SN.json
  templates/tempGen/tempGen.py
  templates/tempGen/template-daily.json
  templates/tempGen/template.json
  templates/terraform-deployment-steps-daily.yaml
  templates/terraform-deployment-steps.yaml
  templates/test-case-template-update.yaml
  templates/variables.yaml
Labels: enhancement

#1024 [BUG] Support multiple disks for app tier
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
Labels: bug

#1025 Add tf timeout in pipeline testing
  .pipeline/tf-deployer-test.yml
  .pipeline/tf-integration-test.yml
  .pipeline/tf-release.yml
  .pipeline/tf-saplandscape-test.yml
  .pipeline/tf-saplib-test.yml
  .pipeline/tf-sapsystem-anydb-test.yml
  .pipeline/tf-sapsystem-test.yml
Labels: Pipeline

#1026 Support bringing your own keyvault for SAP System
  deploy/terraform/run/sap_system/module.tf
  deploy/terraform/run/sap_system/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/key_vault_sap_system.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
Labels: enhancement

#1027 Added a check that replaces "_" in VNet names
  deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf
Labels: bug
