Repository Azure/sap-hana, pull requests merged in 2021-01, with the labels that each got.

#1030 Define the container names in the naming module
  deploy/terraform/bootstrap/sap_library/saplibrary_full.json
  deploy/terraform/run/sap_landscape/variables_local.tf
  deploy/terraform/run/sap_library/variables_local.tf
  deploy/terraform/run/sap_system/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_library/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf
Labels: enhancement

#1033 Move all SSH keys from submodules to common_infrastructure
  deploy/terraform/run/sap_system/module.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-observer.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/vm-hdb.tf
Labels: enhancement

#1029 Add support for SDU specific SSH keys
  deploy/terraform/run/sap_system/output.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/key_vault_sap_system.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
Labels: enhancement

#1040 Add more rules when pulling ssh key
  .pipeline/templates/ansible/ansible-playbook-steps.yml
Labels: Ansible, HOTFIX, Pipeline, bug

#1042 Add master to test pipeline to verify hotfix
  .pipeline/tf-deployer-test.yml
  .pipeline/tf-saplandscape-test.yml
  .pipeline/tf-saplib-test.yml
  .pipeline/tf-sapsystem-anydb-test.yml
  .pipeline/tf-sapsystem-test.yml
Labels: Pipeline

#1045 [HOTFIX] Revert change to use standard load balancer everywhere
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
Labels: Ansible, HOTFIX, Terraform

#1047 Renaming sshkey block to authentication AB#137
  .pipeline/templates/deployer/create-deployer-steps.yml
  deploy/terraform/bootstrap/sap_deployer/module.tf
  deploy/terraform/bootstrap/sap_deployer/variables_global.tf
  deploy/terraform/bootstrap/sap_library/module.tf
  deploy/terraform/bootstrap/sap_library/variables_local.tf
  deploy/terraform/run/sap_deployer/module.tf
  deploy/terraform/run/sap_deployer/variables_global.tf
  deploy/terraform/run/sap_landscape/module.tf
  deploy/terraform/run/sap_landscape/providers.tf
  deploy/terraform/run/sap_landscape/saplandscape.json
  deploy/terraform/run/sap_landscape/saplandscape_full.json
  deploy/terraform/run/sap_landscape/variables_global.tf
  deploy/terraform/run/sap_library/module.tf
  deploy/terraform/run/sap_library/variables_local.tf
  deploy/terraform/run/sap_system/module.tf
  deploy/terraform/run/sap_system/sapsystem_full.json
  deploy/terraform/run/sap_system/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_deployer/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_deployer/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_deployer/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_library/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/key_vault_sap_system.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/output_files/variables_global.tf
  documentation/SAP_Automation_on_Azure/Software_Documentation/workshops/standard/templates/NP-EUS2-SAP00-INFRASTRUCTURE.json
Labels: enhancement

#1020 [CREDENTIALS] Providing a way to provide credentials to landscape AB#137
  .pipeline/templates/saplandscape/create-saplandscape-steps.yml
  deploy/terraform/run/sap_landscape/module.tf
  deploy/terraform/run/sap_landscape/output.tf
  deploy/terraform/run/sap_landscape/providers.tf
  deploy/terraform/run/sap_landscape/saplandscape.json
  deploy/terraform/run/sap_landscape/saplandscape_full.json
  deploy/terraform/run/sap_landscape/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf
  deploy/terraform/terraform-units/modules/sap_landscape/outputs.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_local.tf
Labels: enhancement

#1048 Add Validation for SAP System
  CODEOWNERS
  deploy/terraform/run/sap_system/variables_global.tf
Labels: enhancement

#1037 [VALIDATIONJ] Add Validation for SAP Landscape AB#134
  deploy/terraform/run/sap_landscape/variables_global.tf
  deploy/terraform/run/sap_landscape/variables_local.tf
Labels: enhancement

#1032 Adding validation logic for the deployer AB#134
  deploy/terraform/bootstrap/sap_deployer/module.tf
  deploy/terraform/bootstrap/sap_deployer/variables_global.tf
  deploy/terraform/run/sap_deployer/module.tf
  deploy/terraform/run/sap_deployer/variables_global.tf
Labels: enhancement

#1034 Validation checks for SAP Library
  deploy/terraform/bootstrap/sap_library/saplibrary_full.json
  deploy/terraform/bootstrap/sap_library/variables_global.tf
  deploy/terraform/run/sap_library/saplibrary_full.json
  deploy/terraform/run/sap_library/variables_global.tf
Labels: enhancement
