Repository Azure/sap-hana, pull requests merged in 2021-03, with the labels that each got.

#1079 [SQL] Add a witness storage account AB#132
  deploy/terraform/run/sap_landscape/module.tf
  deploy/terraform/run/sap_landscape/output.tf
  deploy/terraform/run/sap_landscape/providers.tf
  deploy/terraform/run/sap_landscape/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_landscape/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf
  deploy/terraform/terraform-units/modules/sap_landscape/outputs.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/output.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/resourcegroup.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf
Labels: enhancement

#1077 Providing more options for app tier VM sizing AB#144
  deploy/configs/app_sizes.json
Labels: enhancement

#1076 Pushing the deployment scripts to master
  .pipeline/README.MD
  deploy/configs/version.txt
  deploy/scripts/install_deployer.sh
  deploy/scripts/install_library.sh
  deploy/scripts/install_workloadzone.sh
  deploy/scripts/installer.sh
  deploy/scripts/prepare_region.sh
  deploy/scripts/pwsh/SAPDeploymentUtilities/.gitignore
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/helper_functions.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/new_deploymentregion.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/new_sapdeployer.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/new_sapdeployment.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/new_saplibrary.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/new_sapworkloadzone.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/set_secrets.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Output/SAPDeploymentUtilities/SAPDeploymentUtilities.psd1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Output/SAPDeploymentUtilities/SAPDeploymentUtilities.psm1
  deploy/scripts/pwsh/SAPDeploymentUtilities/README.md
  deploy/scripts/pwsh/SAPDeploymentUtilities/SAPDeploymentUtilities.build.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/SAPDeploymentUtilities.psd1
  deploy/scripts/pwsh/SAPDeploymentUtilities/SAPDeploymentUtilities.psm1
  deploy/scripts/set_secrets.sh
  deploy/terraform/bootstrap/sap_deployer/output.tf
  deploy/terraform/bootstrap/sap_deployer/variables_local.tf
  deploy/terraform/bootstrap/sap_library/imports.tf
  deploy/terraform/bootstrap/sap_library/output.tf
  deploy/terraform/bootstrap/sap_library/variables_global.tf
  deploy/terraform/bootstrap/sap_library/variables_local.tf
  deploy/terraform/run/sap_deployer/deployer.json
  deploy/terraform/run/sap_deployer/output.tf
  deploy/terraform/run/sap_deployer/variables_local.tf
  deploy/terraform/run/sap_landscape/output.tf
  deploy/terraform/run/sap_landscape/providers.tf
  deploy/terraform/run/sap_landscape/variables_local.tf
  deploy/terraform/run/sap_library/output.tf
  deploy/terraform/run/sap_library/providers.tf
  deploy/terraform/run/sap_library/variables_local.tf
  deploy/terraform/run/sap_system/output.tf
  deploy/terraform/run/sap_system/variables_local.tf
  documentation/SAP_Automation_on_Azure/Process_Documentation/Deployment_folder_structure.md
  documentation/SAP_Automation_on_Azure/Process_Documentation/Deployment_scripts.md
  documentation/SAP_Automation_on_Azure/Process_Documentation/Folderstructure.png
  documentation/SAP_Automation_on_Azure/Process_Documentation/Getting started with the SAP Deployment Automation framework.md
  documentation/SAP_Automation_on_Azure/Process_Documentation/Getting_started_with_the_SAP_Deployment_Automation_bash.md
  documentation/SAP_Automation_on_Azure/Process_Documentation/Getting_started_with_the_SAP_Deployment_Automation_cloudshell.md
  documentation/SAP_Automation_on_Azure/Process_Documentation/Getting_started_with_the_SAP_Deployment_Automation_pwsh.md
Labels: Orchestration

#1081 [HOTFIX] Add the ability to retain the NIC order from older deployments
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
Labels: HOTFIX

#1082 [IMPROVEMENT] Flexible app tier sizing
  deploy/configs/app_sizes.json
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
Labels: enhancement

#1084 Update Pipeline to use Terraform 0.14.7
  .pipeline/templates/util/prepare-agent.yml
  deploy/terraform/terraform-units/modules/sap_deployer/vm-deployer.tf
Labels: Pipeline

#1078 [ORCHESTRATION] Deploy without the deployer AB#125
  deploy/terraform/bootstrap/sap_library/imports.tf
  deploy/terraform/bootstrap/sap_library/module.tf
  deploy/terraform/bootstrap/sap_library/variables_global.tf
  deploy/terraform/bootstrap/sap_library/variables_local.tf
  deploy/terraform/run/sap_landscape/imports.tf
  deploy/terraform/run/sap_landscape/module.tf
  deploy/terraform/run/sap_landscape/variables_global.tf
  deploy/terraform/run/sap_landscape/variables_local.tf
  deploy/terraform/run/sap_library/imports.tf
  deploy/terraform/run/sap_library/module.tf
  deploy/terraform/run/sap_library/variables_global.tf
  deploy/terraform/run/sap_library/variables_local.tf
  deploy/terraform/run/sap_system/imports.tf
  deploy/terraform/run/sap_system/module.tf
  deploy/terraform/run/sap_system/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_landscape/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_library/storage_accounts.tf
  deploy/terraform/terraform-units/modules/sap_library/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/outputs.tf
Labels: enhancement

#1080 [ORCHESTRATION] powershell updates AB#125
  .gitignore
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/new_deploymentregion.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/new_sapdeployer.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/new_sapdeployment.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/new_saplibrary.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Internal/set_secrets.ps1
  deploy/scripts/pwsh/SAPDeploymentUtilities/Output/SAPDeploymentUtilities/SAPDeploymentUtilities.psm1
  deploy/scripts/set_secrets.sh
Labels: Orchestration

#1083 [TF] Terraform v0.14.7 support
  deploy/terraform/run/sap_system/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_deployer/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf
  deploy/terraform/terraform-units/modules/sap_library/key_vault.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/key_vault_sap_system.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/infrastructure.tf
Labels: Terraform

#1085 [RATIONALIZATION]Clean up deployer outputs
  deploy/terraform/bootstrap/sap_deployer/output.tf
  deploy/terraform/run/sap_deployer/output.tf
  deploy/terraform/terraform-units/modules/sap_landscape/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_library/variables_local.tf
Labels: Rationalization, Terraform

#1088 Documentation updates
  documentation/SAP_Automation_on_Azure/readme.md
Labels: Documentation

#1089 Documentation updates
  documentation/SAP_Automation_on_Azure/readme.md
  documentation/SAP_Automation_on_Azure/table_of_contents.md
Labels: Documentation

#1087 [ENHANCEMENT] Don't create AVSets if not needed
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/vm-hdb.tf
Labels: enhancement

#1090 [ENHANCEMENT]kimforss-add-asg-support
  deploy/terraform/run/sap_system/module.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/vm-hdb.tf
Labels: enhancement

#1091 Add multiprovider support for landscape
  deploy/terraform/run/sap_landscape/module.tf
  deploy/terraform/run/sap_landscape/providers.tf
  deploy/terraform/terraform-units/modules/sap_landscape/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_landscape/iscsi.tf
  deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf
  deploy/terraform/terraform-units/modules/sap_landscape/providers.tf
Labels: enhancement

#1092 [ENHANCEMENT] Add dynamic ipaddress for deployer
  deploy/terraform/bootstrap/sap_deployer/deployer.json
  deploy/terraform/bootstrap/sap_deployer/deployer_full.json
  deploy/terraform/run/sap_deployer/deployer.json
  deploy/terraform/run/sap_deployer/deployer_full.json
  deploy/terraform/terraform-units/modules/sap_deployer/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_deployer/vm-deployer.tf
Labels: enhancement

#1093 [ENHANCEMENT]Add multi subscription support to sapsystem
  deploy/terraform/run/sap_system/module.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/providers.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-observer.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/nsg-app-subnet.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/nsg-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/providers.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/key_vault_sap_system.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/nsgs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/providers.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/vm-anchor.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/providers.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/vm-hdb.tf
  deploy/terraform/terraform-units/modules/sap_system/output_files/inventory.tf
  deploy/terraform/terraform-units/modules/sap_system/output_files/providers.tf
Labels: enhancement

#1094 [Enhancement] Move the zonal ppg and avset naming to naming module
  deploy/scripts/validate.sh
  deploy/terraform/terraform-units/modules/sap_namegenerator/output.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/ppg-avset.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/resourcegroup.tf
  deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/infrastructure.tf
Labels: enhancement

#1096 ENHANCEMENT Support 4 IPs for HA Win CS
  deploy/terraform/terraform-units/modules/sap_namegenerator/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
Labels: enhancement

#1098 [ENHANCEMENT] Provide the ability to control the placement of the NSGs and ASGs
  deploy/terraform/terraform-units/modules/sap_system/app_tier/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/nsg-app-subnet.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/nsg-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/infrastructure.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/nsgs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
Labels: enhancement
